/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COMMA = 2,
  sym_line_comment = 3,
  sym_block_comment = 4,
  sym_rem_comment = 5,
  sym_single_quoted_string = 6,
  sym_double_quoted_string = 7,
  sym_bracket_field = 8,
  sym_integer = 9,
  sym_float = 10,
  sym_macro = 11,
  sym_comparison_operator = 12,
  sym_arithmetic_operator = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  sym_identifier = 16,
  sym_source_file = 17,
  sym__item = 18,
  sym_number = 19,
  sym_parenthesized = 20,
  sym_function_call = 21,
  aux_sym_source_file_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_rem_comment] = "rem_comment",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_bracket_field] = "bracket_field",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_macro] = "macro",
  [sym_comparison_operator] = "comparison_operator",
  [sym_arithmetic_operator] = "arithmetic_operator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_number] = "number",
  [sym_parenthesized] = "parenthesized",
  [sym_function_call] = "function_call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_rem_comment] = sym_rem_comment,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_bracket_field] = sym_bracket_field,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_macro] = sym_macro,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_arithmetic_operator] = sym_arithmetic_operator,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_number] = sym_number,
  [sym_parenthesized] = sym_parenthesized,
  [sym_function_call] = sym_function_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_rem_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_field] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 1,
        '$', 3,
        '\'', 2,
        '(', 30,
        ')', 31,
        ',', 14,
        '/', 29,
        ';', 13,
        '<', 27,
        '=', 25,
        '>', 26,
        '[', 8,
        'R', 32,
        'r', 32,
        '&', 28,
        '*', 28,
        '+', 28,
        '-', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead == '#' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(18);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(24);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == ';') ADVANCE(17);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == ']') ADVANCE(20);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_rem_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_single_quoted_string);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_double_quoted_string);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_bracket_field);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_macro);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comparison_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comparison_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_comparison_operator);
      if (('<' <= lookahead && lookahead <= '>')) ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_arithmetic_operator);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_arithmetic_operator);
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(15);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (lookahead == '#' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(34);
      if (lookahead == '#' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '#' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(1),
    [sym_double_quoted_string] = ACTIONS(1),
    [sym_bracket_field] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_macro] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_arithmetic_operator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__item] = STATE(4),
    [sym_number] = STATE(4),
    [sym_parenthesized] = STATE(4),
    [sym_function_call] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_COMMA] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(7),
    [sym_double_quoted_string] = ACTIONS(7),
    [sym_bracket_field] = ACTIONS(7),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(7),
    [sym_comparison_operator] = ACTIONS(7),
    [sym_arithmetic_operator] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__item] = STATE(2),
    [sym_number] = STATE(2),
    [sym_parenthesized] = STATE(2),
    [sym_function_call] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
    [sym_bracket_field] = ACTIONS(21),
    [sym_integer] = ACTIONS(24),
    [sym_float] = ACTIONS(27),
    [sym_macro] = ACTIONS(21),
    [sym_comparison_operator] = ACTIONS(21),
    [sym_arithmetic_operator] = ACTIONS(30),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(19),
    [sym_identifier] = ACTIONS(36),
  },
  [STATE(3)] = {
    [sym__item] = STATE(5),
    [sym_number] = STATE(5),
    [sym_parenthesized] = STATE(5),
    [sym_function_call] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_SEMI] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(39),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(39),
    [sym_double_quoted_string] = ACTIONS(39),
    [sym_bracket_field] = ACTIONS(39),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(39),
    [sym_comparison_operator] = ACTIONS(39),
    [sym_arithmetic_operator] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(43),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym__item] = STATE(2),
    [sym_number] = STATE(2),
    [sym_parenthesized] = STATE(2),
    [sym_function_call] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(45),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(47),
    [sym_double_quoted_string] = ACTIONS(47),
    [sym_bracket_field] = ACTIONS(47),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(47),
    [sym_comparison_operator] = ACTIONS(47),
    [sym_arithmetic_operator] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym__item] = STATE(2),
    [sym_number] = STATE(2),
    [sym_parenthesized] = STATE(2),
    [sym_function_call] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(47),
    [sym_double_quoted_string] = ACTIONS(47),
    [sym_bracket_field] = ACTIONS(47),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(47),
    [sym_comparison_operator] = ACTIONS(47),
    [sym_arithmetic_operator] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(51),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(6)] = {
    [sym__item] = STATE(7),
    [sym_number] = STATE(7),
    [sym_parenthesized] = STATE(7),
    [sym_function_call] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_SEMI] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(53),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(53),
    [sym_double_quoted_string] = ACTIONS(53),
    [sym_bracket_field] = ACTIONS(53),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(53),
    [sym_comparison_operator] = ACTIONS(53),
    [sym_arithmetic_operator] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(57),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(7)] = {
    [sym__item] = STATE(2),
    [sym_number] = STATE(2),
    [sym_parenthesized] = STATE(2),
    [sym_function_call] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_SEMI] = ACTIONS(47),
    [anon_sym_COMMA] = ACTIONS(47),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(47),
    [sym_double_quoted_string] = ACTIONS(47),
    [sym_bracket_field] = ACTIONS(47),
    [sym_integer] = ACTIONS(9),
    [sym_float] = ACTIONS(11),
    [sym_macro] = ACTIONS(47),
    [sym_comparison_operator] = ACTIONS(47),
    [sym_arithmetic_operator] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_RPAREN] = ACTIONS(59),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(61),
    [anon_sym_COMMA] = ACTIONS(61),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(61),
    [sym_double_quoted_string] = ACTIONS(61),
    [sym_bracket_field] = ACTIONS(61),
    [sym_integer] = ACTIONS(63),
    [sym_float] = ACTIONS(61),
    [sym_macro] = ACTIONS(61),
    [sym_comparison_operator] = ACTIONS(61),
    [sym_arithmetic_operator] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_RPAREN] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_SEMI] = ACTIONS(65),
    [anon_sym_COMMA] = ACTIONS(65),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(65),
    [sym_double_quoted_string] = ACTIONS(65),
    [sym_bracket_field] = ACTIONS(65),
    [sym_integer] = ACTIONS(67),
    [sym_float] = ACTIONS(65),
    [sym_macro] = ACTIONS(65),
    [sym_comparison_operator] = ACTIONS(65),
    [sym_arithmetic_operator] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_RPAREN] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_SEMI] = ACTIONS(71),
    [anon_sym_COMMA] = ACTIONS(71),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(71),
    [sym_double_quoted_string] = ACTIONS(71),
    [sym_bracket_field] = ACTIONS(71),
    [sym_integer] = ACTIONS(73),
    [sym_float] = ACTIONS(71),
    [sym_macro] = ACTIONS(71),
    [sym_comparison_operator] = ACTIONS(71),
    [sym_arithmetic_operator] = ACTIONS(73),
    [anon_sym_LPAREN] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_SEMI] = ACTIONS(75),
    [anon_sym_COMMA] = ACTIONS(75),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(75),
    [sym_double_quoted_string] = ACTIONS(75),
    [sym_bracket_field] = ACTIONS(75),
    [sym_integer] = ACTIONS(77),
    [sym_float] = ACTIONS(75),
    [sym_macro] = ACTIONS(75),
    [sym_comparison_operator] = ACTIONS(75),
    [sym_arithmetic_operator] = ACTIONS(77),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [sym_identifier] = ACTIONS(77),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_SEMI] = ACTIONS(79),
    [anon_sym_COMMA] = ACTIONS(79),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(79),
    [sym_double_quoted_string] = ACTIONS(79),
    [sym_bracket_field] = ACTIONS(79),
    [sym_integer] = ACTIONS(81),
    [sym_float] = ACTIONS(79),
    [sym_macro] = ACTIONS(79),
    [sym_comparison_operator] = ACTIONS(79),
    [sym_arithmetic_operator] = ACTIONS(81),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [sym_identifier] = ACTIONS(81),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [anon_sym_SEMI] = ACTIONS(83),
    [anon_sym_COMMA] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_rem_comment] = ACTIONS(3),
    [sym_single_quoted_string] = ACTIONS(83),
    [sym_double_quoted_string] = ACTIONS(83),
    [sym_bracket_field] = ACTIONS(83),
    [sym_integer] = ACTIONS(85),
    [sym_float] = ACTIONS(83),
    [sym_macro] = ACTIONS(83),
    [sym_comparison_operator] = ACTIONS(83),
    [sym_arithmetic_operator] = ACTIONS(85),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [sym_identifier] = ACTIONS(85),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_line_comment,
      sym_block_comment,
      sym_rem_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__item, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_qlik(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "qlik",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
